# Generated by Django 3.0.2 on 2020-02-19 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget_account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('created_utc', models.DateField(auto_now_add=True)),
                ('modefied_utc', models.DateField(auto_now=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_utc', models.DateField(auto_now_add=True)),
                ('modefied_utc', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Income_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_utc', models.DateField(auto_now_add=True)),
                ('modefied_utc', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Budget_expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('month', models.IntegerField(choices=[(0, 'January'), (1, 'February'), (2, 'March'), (3, 'April'), (4, 'May'), (5, 'June'), (6, 'July'), (7, 'August'), (8, 'September'), (9, 'October'), (10, 'November'), (11, 'December')])),
                ('created_utc', models.DateField(auto_now_add=True)),
                ('modefied_utc', models.DateField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='life.Budget_account')),
                ('expenseType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='life.Expense_type')),
            ],
        ),
        migrations.CreateModel(
            name='Budget_config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(0, 'January'), (1, 'February'), (2, 'March'), (3, 'April'), (4, 'May'), (5, 'June'), (6, 'July'), (7, 'August'), (8, 'September'), (9, 'October'), (10, 'November'), (11, 'December')])),
                ('created_utc', models.DateField(auto_now_add=True)),
                ('modefied_utc', models.DateField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='life.Budget_account')),
            ],
        ),
    ]
