# Generated by Django 3.0.2 on 2020-02-19 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget_account',
            old_name='modefied_utc',
            new_name='modified_utc',
        ),
        migrations.RenameField(
            model_name='budget_config',
            old_name='modefied_utc',
            new_name='modified_utc',
        ),
        migrations.RenameField(
            model_name='budget_expense',
            old_name='modefied_utc',
            new_name='modified_utc',
        ),
        migrations.RenameField(
            model_name='expense_type',
            old_name='modefied_utc',
            new_name='modified_utc',
        ),
        migrations.RenameField(
            model_name='income_type',
            old_name='modefied_utc',
            new_name='modified_utc',
        ),
    ]
