# Generated by Django 3.0.2 on 2020-02-19 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('life', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='budgetAccount',
            new_name='Budget_account',
        ),
        migrations.CreateModel(
            name='Budget_expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='life.Budget_account')),
            ],
        ),
    ]
